### ISSUE TITLE
Interrupt enable and mask register operation failed

### ISSUE THREAD

**Issue by NoahCSHN** [Blebowski/CTU-CAN-FD#1]
Hello guys!
I'm a freshmen for CAN FD bus and I'm using your IP for learning how to control a CAN FD core.
I use a Xilinx ZYNQ7000 FPGA Chip(xc7z030ffg676-2) for implementation of my project.
I synthesis your IP core use vivado sucessfully and add the netlist file(edf) to my project.
I connected the FPGA device to a CAN Analyzer and wrote a simple initialization software.
It seems that everthing is running properly but the interrupt enable and mask register(address: 0x14,0x18,0x1c,0x20).
I configure the IP core as your DATASHEET(CANFD_DATASET.pdf). And I found 2 strange point.
1. When I configure the interrupt, I wrote 0xFFFF to address 0x14 to enable all interrupt. JUST AFTER i wrote to it, I read 0x14 but got the value 0x00000000, both the interrupt ena_set and mask_set register has the same problem(read always return 0x00000000);
2. When I configure everything but interrupt and enable the bus by writing '1' to SETTING[ENA], I can be sure that the bus is Error Active by reading the FAULT_STATE register as 0x01, but the interrupt did not become valid.

**Comment by Blebowski** [comment]
Please let me know if the issue disappeared in your use-case with the latest version so that I can close the issue.

**Comment by Blebowski** [comment]
Hello Noah,

with regards to your comments:

1. Interrupt port is registered. CTU CAN FD has "res_n" signal. If you properly drive this signal low during initialization of your system, there should be no "uncertain values" on "int" output. Note that CTU CAN FD internally resynchronizes the reset, therefore, if you de-assert reset, it lasts for 2-3 clock cycles before you can access the core.

2. There are two ways of downloading the core:
     a) Clone the Gitlab repo, and pick the files from "src" folder, in here no file list is provided.
     b) Download "Delivery package" (see README on Gitlab), this will include exported RTL and Testbench + related file lists.

**Comment by Blebowski** [comment]
I am going to close the issue as there is nothing really to fix here.
